### ISSUE TITLE
boost test too slow...skip it ?

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#183]
Hi Rado,

developer (like me) wants to run quickly autocmake tests. However, "test/test.py::test_boost_libs" take too long due to missing packages and the computer is downloading/compiling them.

Would be good to skip this test if packages are not installed and/or provide own flag for running tests dependent on 'exotic' packages, or flags confirming downloading of missing source modules (boost and whatever).

Also, concerning requirements:

https://github.com/coderefinery/autocmake/blob/master/requirements.txt

would be good to add about most basic packages needed to be installed to be able to run autocmake 'basic'.

Comments ?

**Comment by miroi** [comment]
Or as to the autocmake testing: let us have categories of tests, by default let it run quick tests only.

**Comment by bast** [comment]
You can exclude tests with `-k`: http://doc.pytest.org/en/latest/usage.html#specifying-tests-selecting-tests

Does this solve the problem?

**Comment by bast** [comment]
What packages are missing in `requirements.txt`?

**Comment by miroi** [comment]
Fine, excluding is the viable option, closing this issue.
