### ISSUE TITLE
ERROR: could not fetch //github.com/coderefinery/autocmake/raw/master/lib/config.py

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#184]
Hi Rado,

I tried to update autocmake modules; however, git fetch problem (see below). 

Also, how about provide version to update.py so that user knows if there are newer modules in the repository  ?

~~~
milias@login.grid.umb.sk:~/Work/qch/software/smaller_software_projects/mathlibs-tester_devel/mathlibs-tester_devel/cmake/.python update.py --self
- fetching lib/config.py
ERROR: could not fetch //github.com/coderefinery/autocmake/raw/master/lib/config.py
milias@login.grid.umb.sk:~/Work/qch/software/smaller_software_projects/mathlibs-tester_devel/mathlibs-tester_devel/cmake/.python update.py --version
ERROR: --version is not a directory
milias@login.grid.umb.sk:~/Work/qch/software/smaller_software_projects/mathlibs-tester_devel/mathlibs-tester_devel/cmake/.
~~~

**Comment by bast** [comment]
I don't know what the reason for the fetching problem is. It is not Git. And it is a good point that things should be versioned. I have yet to figure out a good way how to version the scripts and the modules in a coherent way. Suggestions are welcome.

**Comment by miroi** [comment]
Hi,

i) solved through downloading fresh update.py "milias@login.grid.umb.sk:~/Work/qch/software/smaller_software_projects/mathlibs-tester_devel/mathlibs-tester_devel/cmake/.wget https://github.com/coderefinery/autocmake/raw/stable-0.x/update.py 
"
So, the older  "update.py --self" does not always work, safe way is downloading fresh file.

ii) Concerning "update.py --version" ? I would use the same version number as is of the main autocmake.

Closing as solved.

**Comment by miroi** [comment]
well, at least i would let it flush message for --self  'in case of error download update.py manually...'
