### ISSUE TITLE
update.py: /usr/bin/env python

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#185]
Hi Rado,

again problem with python installation: admin can not install 2.7.x in order not to break current system installation.

Instead he provided *alias python=.../python2.7* workaround, which is not in work for */usr/bin/env python* of update.py - this command always catches system installed python of lower version.

Any help, please ?

**Comment by bast** [comment]
Hi Miro, what I would do here is to install a virtual environment with `--python=<path to the one you want>` and source that one. Then it should work. Please let me know whether this worked for you.

**Comment by bast** [comment]
I consider this one as solved. If not, please reopen.
