### ISSUE TITLE
git-info-cmake in module reference ?

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#187]
Hi,

in https://autocmake.readthedocs.io/en/latest/module-reference.html#git-info-cmake

shouldn't  be there "- "%(url_root)modules/git_info/git_info.cmake" instead of 
"- "%(url_root)modules/git_info/git_info.h.in""  ?

**Comment by bast** [comment]
I think it is correct. But perhaps I don't see the problem. Why do you think it is wrong?

**Comment by miroi** [comment]
you have there   - "%(url_root)modules/git_info/git_info.h.in" ....

**Comment by bast** [comment]
Yes, this is a file that this module requires and therefore it needs to be fetched.
