### ISSUE TITLE
Finish configuration when MATH_LIB_SEARCH_ORDER is not used by the project.

### ISSUE THREAD

**Issue by uachstno** [coderefinery/autocmake#195]
When turning off blas and lapack detection CMake will waarn that MATH_LIB_SEARCH_ORDER is not used:

CMake Warning:
  Manually-specified variables were not used by the project:

   MATH_LIB_SEARCH_ORDER

Which is in principle ok, but it is the last what cmake prints on output. Lines
 
configure step is done
   now you need to compile the sources:
   $ cd build-t1
   $ make

are missing. So the configuration is not finished. I think most of the configuration is done since I can compile the code. But for example setup_command file is missing.

**Comment by bast** [comment]
Thanks! Just for future reference the setup line was:
```
$ ./setup --fc=gfortran --explicit-libs="-L/usr/lib -llapack -lblas" --blas=off --lapack=off  build-ttt
```
