### ISSUE TITLE
missing:  PYTHON_LIBRARY on CentOS 7

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#197]
New CentOS 7 x86-64 server, and I don't know which python-xxx packages are for PythonLibs...

Any help, please ?

~~~
milias@adf1:~/Work/programming/autocmake/test/python_interpreter/build-2017-05-18-22-22-57/.cmake ..
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARY) 
CMake Error at /home/milias/Work/programming/autocmake/modules/python_libs.cmake:78 (message):
  Could NOT find PythonLibs
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)


-- Configuring incomplete, errors occurred!
~~~

**Comment by bast** [comment]
Can you describe the Python environment a bit? Are there Python libraries and headers available? Maybe `python-dev` is not installed?

**Comment by miroi** [comment]
Hi,
solved with "yum install python-devel.x86_64".  Would be good to mention necesary packages in https://autocmake.readthedocs.io/en/latest/general/requirements.html , 

plus mentioningthem  in cmake error messages, like 

~~~
Could NOT find PythonLibs ... did you install python-dev package ?
~~~

**Comment by bast** [comment]
OK - I will add some docs. This is only relevant for people actually running the tests but still we can mention it somewhere.

**Comment by miroi** [comment]
ah,

another problem with new CentOS server - when running tests, openmp fails due to this error message below.

What packages are missing ? Would be good to have more informative error messages to that admin quickly knows what package install....


~~~
E         - CMake Error at /usr/share/cmake/Modules/FindOpenMP.cmake:169 (message):
E         -   FindOpenMP requires C or CXX language to be enabled
E         - Call Stack (most recent call first):
E         -   /home/milias/Work/programming/autocmake/modules/omp.cmake:26 (find_package)
E         -   CMakeLists.txt:24 (include)
~~~

**Comment by bast** [comment]
The OMP part deserves an own issue.
