### ISSUE TITLE
C++11 in default GNU C++ plugin

### ISSUE THREAD

**Issue by robertodr** [coderefinery/autocmake#198]
Should the default GNU C++ plugin use the `-std=c++11` flag?
https://github.com/coderefinery/autocmake/blob/master/compilers/GNU.CXX.cmake

**Comment by bast** [comment]
I thought at some point that it was a good idea. But apparently not? Would you prefer this not to be a default flag?

**Comment by robertodr** [comment]
I am not sure. Sadly enough, C++11 compliance still crosses out a lot of proprietary compilers from being usable.

**Comment by bast** [comment]
OK - for consistency it would then make sense to take it out, right?

**Comment by robertodr** [comment]
That would be my preferred solution. There can be an extra plugin to adjust the C++ standard version, which would check compiler version and standard library, [like here](https://github.com/psi4/psi4/blob/master/cmake/custom_cxxstandard.cmake) The plugin should only kick in if the CMake version is less than 3.0, however.

**Comment by bast** [comment]
I agree - I will remove the flag shortly.

**Comment by robertodr** [comment]
thanks! :+1:
