### ISSUE TITLE
[enhancement] save text file with the setup command

### ISSUE THREAD

**Issue by miroi** [coderefinery/autocmake#204]
Hi Rado,

Some time ago I compiled Dirac with plenty of *setup* flags (parallel, exotic library, extra compiler flags etc):
~~~
production_trunk/build_openmpi_intel15_i8_xhost_openblas
~~~
However, now I can not remember the exact *setup* parameters for the working dirac.x executable.

So I advocate the enhancement - let *setup* saves the file with the exact command and flags into build/ directory. Let's name this file as **setup_command.txt** or similar.

Comments ?

**Comment by bast** [comment]
That's a good idea but it should already happen:
https://github.com/coderefinery/autocmake/blob/master/autocmake/configure.py#L136-L142

If this does not happen, then I think this is a bug.

**Comment by miroi** [comment]
It happens ! The **setup_command** is there, in the DIRAC build directory. Closing this issue.

**Comment by bast** [comment]
:-)

**Comment by miroi** [comment]
I think the reason for not having *setup_command* in the build directory was that autocmake was not updated. Hmm. It would be good to have printed autocmake version in setup, I will open new issue for that.

**Comment by bast** [comment]
Version info is a good point but the `setup_command` has been there "forever".
