### ISSUE TITLE
[Licensing] Make clear licensing of Python code and downloaded plugins

### ISSUE THREAD

**Issue by robertodr** [coderefinery/autocmake#211]
As mentioned by @jsspencer in hande-qmc/hande#2, it is not clear by skimming through Autocmake-related files what their license is. I suggest to prepend the Python code and the Autocmake plugins with the BSD-3-Clause license header. In addition, it might also be a good idea to generate or download a brief `README.md` in the `cmake` directory that makes clear that the Autocmake project is used to generate parts of the CMake infrastructure. I propose the following as content:
```
The CMake infrastructure for this project is generated using [Autocmake] by Radovan Bast, Jonas Juselius and contributors.
The `update.py` Python script and the contents of the directories `autocmake` and `downloaded` are licensed under the terms of the [BSD-3-Clause license], unless otherwise stated.

[Autocmake]: http://autocmake.readthedocs.io/en/latest/
[BSD-3-Clause license]: https://tldrlegal.com/license/bsd-3-clause-license-(revised)
```

**Comment by bast** [comment]
Thanks. Very good suggestion. Working on this.
