### ISSUE TITLE
[Discussion] Splitting infrastructure and components

### ISSUE THREAD

**Issue by bast** [coderefinery/autocmake#214]
Not completely sure this is a good idea but I put it on paper for others to brainstorm and comment: I was thinking whether splitting the "Python part" (update script) and the modules part into two separate repos would be a benefit or a pain. Splitting them could allow to version them separately and would separate concerns (the modules are usable outside of Autocmake and one might want to fork and adapt the modules without having all the rest). But perhaps they should not be versioned separately since they are not fully decoupled thanks to the autocmake.yml part - not sure.

**Comment by robertodr** [comment]
I think the project is at the correct level of granularity right now.

**Comment by bast** [comment]
OK :-) Closing.
