### ISSUE TITLE
[Discussion] Move repo to own org?

### ISSUE THREAD

**Issue by bast** [coderefinery/autocmake#215]
Just wanted to get your feedback: we could move this repo to own "autocmake" org. The motivation would be that now coderefinery people don't really work on autocmake and vice versa. On the other hand the current solution might increase cross-visibility. A separate org could help building a community around cmake/autocmake development. It could also simplify holding autocmake-related repos (see also https://github.com/coderefinery/autocmake/issues/214).

Just wanted to bounce this idea off other people.

**Comment by miroi** [comment]
Yes, I am in favor of "autocmake.org". The "coderefinery" is common house for various projects and autocmake deserves own house.

**Comment by bast** [comment]
Thanks for feedback! What I meant is `github.com/autocmake` as organization.

**Comment by robertodr** [comment]
Are there branding/funding conflicts? Meaning, does it look bad to have Autocmake under CodeRefinery? If not, I'd prefer Autocmake to stay where it is now.

**Comment by bast** [comment]
There is no branding/funding conflict.

**Comment by bast** [comment]
Closing/postponing.
