### ISSUE TITLE
default_build_paths and GNUInstallDirs

### ISSUE THREAD

**Issue by robertodr** [coderefinery/autocmake#228]
Should `default_build_paths.cmake` use `GNUInstallDirs`?
It currently stores binaries under `${CMAKE_BINARY_DIR}/bin` and libraries under `${CMAKE_BINARY_DIR}/lib` but on 64-bit system the latter should rather be `${CMAKE_BINARY_DIR}/lib64`.

**Comment by robertodr** [comment]
The fix would be:
```
include(GNUInstallDirs)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR})
```

**Comment by bast** [comment]
Yes, you are right. Your suggestion is better than the current solution.
