### ISSUE TITLE
Rewrite the options wrappers using cmake_parse_arguments.

### ISSUE THREAD

**Issue by robertodr** [coderefinery/autocmake#236]

**Comment by bast** [comment]
Absolutely. That's the way to go.

**Comment by robertodr** [comment]
You can assign me, so I won't forget.

**Comment by bast** [comment]
Assigned but feel free to un-assign yourself of course. Once the book is out I plan a major overhaul of this repo since many/most aspects are "wrong" :-)

**Comment by robertodr** [comment]
Closed with #237 and #239
